version: '2'

services:
  mongo_with_data:
    build: . # build our own image with sample data
    image: mongo-sample-datasets:dev
  # rockmongo GUI pointed at mongo server with data
    ports:
      - "27017:27017"
